import { Button, VerticalBox, HorizontalBox, LineEdit, TabWidget } from "std-widgets.slint";


export component AppWindow inherits Window {
    min-height: 1000px;
    min-width: 1000px;

    in property <image> oned_img;
    in property <image> twod_img;
    in-out property <string> rule;
    callback submit-clicked();
    callback twod-clicked();
    callback text-edited(string);
    callback text-accepted(string);

    TabWidget {
        Tab {
            title: "2D CA";
            Image {
                source: root.twod_img;
                width: 500px;
                height: 500px;
                image-fit: fill;
                image-rendering: pixelated;
            }
        }

        Tab {
            title: "1D CA";
            VerticalBox {
                HorizontalBox {
                    height: 50px;
                    LineEdit {
                        enabled: true;
                        placeholder-text: "Enter number between 0-255";
                        text: rule;
                        edited(text) => {
                            root.text-edited(text);
                        }
                        accepted(text) => {
                            root.text-accepted(text);
                        }
                    }

                    Button {
                        text: "Generate";
                        clicked => {
                            root.submit-clicked();
                        }
                    }
                }

                Image {
                    source: root.oned_img;
                    width: 500px;
                    height: 500px;
                    image-fit: fill;
                    image-rendering: pixelated;
                }
            }
        }
    }
}
